source 'https://rubygems.org'

gem 'rspec'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'
gem 'capybara'
gem 'cucumber'
gem 'cucumber-sinatra'
gem 'sinatra'
gem 'bcrypt-ruby'
gem 'byebug'
